version: '3.9'

services: 
  app:
    image: fffffatah/heimdall-home-media-system:v1.0.0
    build:
        context: .
        dockerfile: .docker/Dockerfile
    container_name: heimdall
    ports:
        - 8080:80
    volumes:
        - ./src:/var/www/html  
  #   depends_on:
  #       - mysql

  # db:
  #   image: mysql:latest
  #   restart: unless-stopped
  #   container_name: mysql
  #   ports: 
  #     - "3306:3306"
  #   environment:
  #     MYSQL_DATABASE: heimdall
  #     MYSQL_ALLOW_EMPTY_PASSWORD: 1
  #     MYSQL_ROOT_PASSWORD:
  #   volumes:
  #     - ./db:/var/lib/mysql